### ISSUE TITLE
helm chart download URL for 0.5.0 is a bad link

### ISSUE THREAD

**Issue by bdols** [strimzi/drain-cleaner#92]
hello, the download url for strimzi-drain-cleaner 0.5.0 in https://strimzi.io/charts/index.yaml is bad: https://github.com/strimzi/drain-cleaner/releases/tag/0.5.0/strimzi-drain-cleaner-helm-3-chart-0.5.0.tgz  redirects to the github release overview instead of a direct download to the chart artifact.

**Comment by scholzj** [comment]
I opened https://github.com/strimzi/strimzi.github.io/pull/372 to fix it. As an alternative, you can also try the OCI Helm Charts: https://quay.io/organization/strimzi-helm
